# Generated by Django 3.1.1 on 2020-10-04 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='caption',
            field=models.CharField(default=' ', max_length=500),
        ),
    ]
